version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: template-db
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: template
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - template_network

  app:
    build:
      dockerfile: Dockerfile
    container_name: template_app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: template
      DB_USERNAME: root
      DB_PASSWORD: secret
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - template_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: template_nginx
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8888:80"
    networks:
      - template_network
    depends_on:
      - app

  redis:
    image: redis:latest
    container_name: template_redis
    ports:
      - 6382:6379
    networks:
      - template_network
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:


networks:
  template_network:
